### ISSUE TITLE
Using alpaca format for the Databricks Dolly 15k dataset

### ISSUE THREAD

**Issue by ritabratamaiti** [vihangd/alpaca-qlora#5]
Originally using these settings yields an error (because the dolly dataset is not in the default alpaca format)
`python finetune.py --base_model 'openlm-research/open_llama_3b_v2' --data_path 'databricks/databricks-dolly-15k' --num_epochs=3 --cutoff_len=512 --group_by_length --output_dir='./dolly-lora-3b' --lora_r=16 --lora_target_modules='[q_proj,v_proj]'`

I solve this by using the Dolly dataset in alpaca format, (published on the HF hub as 'c-s-ale/dolly-15k-instruction-alpaca-format'). This new training command seems to work now:
`python finetune.py --base_model 'openlm-research/open_llama_3b_v2' --data_path 'c-s-ale/dolly-15k-instruction-alpaca-format' --num_epochs=3 --cutoff_len=512 --group_by_length --output_dir='./dolly-lora-3b' --lora_r=16 --lora_target_modules='[q_proj,v_proj]'`

**Comment by vihangd** [comment]
Yes, I forgot to mention that I used the dolly dataset in the alpaca format. Will update the readme to mention this. Thanks for pointing it out.

**Comment by ritabratamaiti** [comment]
Sure! No issues, if it is more convenient for you, I have merged the alpaca (GPT-4 version), dolly 15k, and code alpaca into a single dataset with various splits (for ease-of-use) here: https://huggingface.co/datasets/Xilabs/instructmix 
You can directly save a split as JSON and pass it to your code (I have verified so)
